import pytest
from jub.client.v2 import JubClient as ClientV2


@pytest.mark.asyncio
async def test_create_from_yaml():
    client = ClientV2(api_url="http://localhost:5000")
    result = await client.create_from_code(file_path="data/2026test.yml")
    assert result.is_ok, f"Expected Ok, got Err: {result.err()}"

@pytest.mark.asyncio
async def test_create_from_yaml_string():
    n_products  = 100
    plot_type   = ["LINE", "BAR", "SCATTER", "BOX", "HISTOGRAM","HEATMAP", "PIE", "AREA", "VIOLIN", "DENSITY"]
    cie10_codes = ["C50_1", "C50_2", "C50_3", "C50_4", "C50_5", "C50_6", "C50_7", "C50_8", "C50_9", "C50_0"]
    for i in range(n_products):
        plot_type_random = plot_type[i % len(plot_type)]
        cie10_codes_random = cie10_codes[i % len(cie10_codes)]
        yml_string = f"""
        products:
          - product_id: "p_01_{i:02d}"
            obs_id: "obs_1"
            name: "Data p_01_{i:02d} - MX {cie10_codes_random} Y2000"
            description: "Autogenerated test product {i}"   
            tags: ["MX", "FEMALE", "Y2000", "{cie10_codes_random}", "{plot_type_random}"]
        """
        client = ClientV2(api_url="http://localhost:5000")
        result = await client.create_from_code(yaml_string=yml_string)
        assert result.is_ok, f"Expected Ok, got Err: {result.err()}"
