name: 📌 Task
description: Track a development or maintenance task.
title: "[task]: "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to describe a development or refactoring task.
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: "Implement X, refactor Y ..."
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What is the intended outcome?
      placeholder: "Improve performance, fix maintainability ..."

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define when this task is considered done.
      options:
        - label: Unit tests added
        - label: Require passing of CI checks (Unit tests, lint/format checks, etc.)
        - label: Documentation updated
