"""
Notifications examples — JUB API v2.

Notifications are generated by the API when background tasks complete,
observatories change state, or products are processed. This example shows
how to read and manage them.

Covers: list_notifications, mark_notification_read,
        mark_all_notifications_read, clear_read_notifications.

Run:
    python examples/v2/cars/notifications/example_notifications.py
"""

import asyncio
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))

from examples.v2.cars.common import get_client, print_result


async def main():
    client = await get_client()

    # --- 1. List all notifications (read + unread) --------------------
    all_result = await client.list_notifications(unread_only=False, limit=50)
    print_result("list_notifications / all", all_result)

    # --- 2. List only unread notifications ----------------------------
    unread_result = await client.list_notifications(unread_only=True, limit=50)
    print_result("list_notifications / unread_only=True", unread_result)

    # --- 3. Mark the first unread notification as read ----------------
    if unread_result.is_ok:
        notifications = unread_result.unwrap()
        if notifications:
            first_id = notifications[0].notification_id
            mark_result = await client.mark_notification_read(first_id)
            print_result(f"mark_notification_read / {first_id}", mark_result)
        else:
            print("[INFO] No unread notifications to mark.")

    # --- 4. Mark all remaining unread notifications as read -----------
    mark_all_result = await client.mark_all_notifications_read()
    print_result("mark_all_notifications_read", mark_all_result)

    # --- 5. Delete all read notifications (house-keeping) -------------
    clear_result = await client.clear_read_notifications()
    print_result("clear_read_notifications", clear_result)


if __name__ == "__main__":
    asyncio.run(main())
